### ISSUE TITLE
update to latest design

### ISSUE THREAD

**Issue by owocki** [oitowork/schelling-point#4]
https://www.figma.com/file/J5pBfGmkXEQUHjSjhplzSq/Schelling-Point?node-id=0%3A1

**Comment by developerfred** [comment]
It's already working, I just needed to confirm it on fleek.
https://schellingpoint.gitcoin.co/

**Comment by owocki** [comment]
word; are you open to making changes to the site as the content comes in?

**Comment by developerfred** [comment]
> word; are you open to making changes to the site as the content comes in?

@owocki Of course, just notify here or by telegram.
